
# XCompose equivalent

special arrow: "->"
special dub arrow: "=>"

special not sign: "¬"
special for all: "∀"
special there exists: "∃"
special there does not exists: "∄"
special not an element of: "∉"
special small element of: "∊"
special logical and: "∧"
special logical or: "∨"
special intersection: "∩"
special union: "∪"
special subset of: "⊂"
special superset of: "⊃"
special not a subset of: "⊄"
special not a superset of: "⊅"
special subset of or equal to: "⊆"
special superset of or equal to: "⊇"
special neither a subset of nor equal to: "⊈"
special neither a superset of nor equal to: "⊉"
special not less than: "≮"
special not greater than: "≯"

special almost equal to: "≈"
special approximately equal to: "≅"
special summation: "∑"
special product: "∏"
special integral: "∫"
special double struck capital q: "ℚ"
special double struck capital r: "ℝ"
special double struck capital z: "ℤ"
special double struck capital c: "ℂ"
special mathematical double struck capital f: "𝔽"
special infinity: "∞"


special tick: "✓"
special cross: "✗"
special square root: "√"

# arrows

special up: "↑"
special left: "←"
special down: "↓"
special right: "→"
special upleft: "↖"
special downleft: "↙"
special downright: "↘"
special upright: "↗"
special hollow up: "⇧"
special hollow left: "⇦"
special hollow down: "⇩"
special hollow right: "⇨"
special hollow upleft: "⬁"
special hollow downleft: "⬃"
special hollow downright: "⬂"
special hollow upright: "⬀"
special bold up: "⬆"
special bold left: "⬅"
special bold down: "⬇"
special bold right: "➡"
special bold upleft: "⬉"
special bold downleft: "⬋"
special bold downright: "⬊"
special bold upright: "⬈"
special up down: "↕"
special left right: "↔"
special upleft downright: "⤡"
special upright downleft: "⤢"
special hollow up down: "⇳"
special hollow left right: "⬄"
special bold up down: "⬍"
special bold left right: "⬌"

# block drawing

special row: "─"
special col: "│"
special topleft: "┌"
special bottomleft: "└"
special bottomright: "┘"
special topright: "┐"
special block: "░"
special tee bottom: "┴"
special tee right: "┤"
special tee top: "┬"
special tee left: "├"
special tee middle: "┼"

special round topleft: "╭"
special round bottomleft: "╰"
special round bottomright: "╯"
special round topright: "╮"

special bold row: "━"
special bold col: "┃"
special bold topleft: "┏"
special bold bottomleft: "┗"
special bold bottomright: "┛"
special bold topright: "┓"
special bold block: "█"
special bold tee bottom: "┻"
special bold tee right: "┫"
special bold tee top: "┳"
special bold tee left: "┣"
special bold tee middle: "╋"

special hollow row: "═"
special hollow col: "║"
special hollow topleft: "╔"
special hollow bottomleft: "╚"
special hollow bottomright: "╝"
special hollow topright: "╗"
special hollow block: "▒"
special hollow tee bottom: "╩"
special hollow tee right: "╣"
special hollow tee top: "╦"
special hollow tee left: "╠"
special hollow tee middle: "╬"

# <Multi_key> <space> <j> <e> : "╵"
# <Multi_key> <space> <j> <s> : "╴"
# <Multi_key> <space> <j> <c> : "╷"
# <Multi_key> <space> <j> <f> : "╶"
# <Multi_key> <space> <k> <e> : "╹"
# <Multi_key> <space> <k> <s> : "╸"
# <Multi_key> <space> <k> <c> : "╻"
# <Multi_key> <space> <k> <f> : "╺"

# <Multi_key> <space> <j> <space> <k> <s> <f> : "╼"
# <Multi_key> <space> <j> <space> <k> <e> <c> : "╽"
# <Multi_key> <space> <j> <space> <k> <f> <s> : "╾"
# <Multi_key> <space> <j> <space> <k> <c> <e> : "╿"
# <Multi_key> <space> <j> <space> <k> <f> <c> : "┎"
# <Multi_key> <space> <j> <space> <k> <c> <s> : "┑"
# <Multi_key> <space> <j> <space> <k> <s> <c> : "┒"
# <Multi_key> <space> <j> <space> <k> <c> <f> : "┍"
# <Multi_key> <space> <j> <space> <k> <e> <f> : "┕"
# <Multi_key> <space> <j> <space> <k> <f> <e> : "┖"
# <Multi_key> <space> <j> <space> <k> <e> <s> : "┙"
# <Multi_key> <space> <j> <space> <k> <s> <e> : "┚"
# <Multi_key> <space> <j> <space> <l> <c> <f> : "╒"
# <Multi_key> <space> <j> <space> <l> <f> <c> : "╓"
# <Multi_key> <space> <j> <space> <l> <c> <s> : "╕"
# <Multi_key> <space> <j> <space> <l> <s> <c> : "╖"
# <Multi_key> <space> <j> <space> <l> <e> <f> : "╘"
# <Multi_key> <space> <j> <space> <l> <f> <e> : "╙"
# <Multi_key> <space> <j> <space> <l> <e> <s> : "╛"
# <Multi_key> <space> <j> <space> <l> <s> <e> : "╜"

# <Multi_key> <j> <space> <k> <s> <f> : "┝"
# <Multi_key> <j> <space> <k> <w> <e> : "┞"
# <Multi_key> <j> <space> <k> <x> <c> : "┟"
# <Multi_key> <space> <j> <k> <f> <s> : "┠"
# <Multi_key> <space> <j> <k> <c> <x> : "┡"
# <Multi_key> <space> <j> <k> <e> <w> : "┢"
# <Multi_key> <j> <space> <k> <s> <s> : "┥"
# <Multi_key> <j> <space> <k> <r> <e> : "┦"
# <Multi_key> <j> <space> <k> <v> <c> : "┧"
# <Multi_key> <space> <j> <k> <s> <s> : "┨"
# <Multi_key> <space> <j> <k> <c> <v> : "┩"
# <Multi_key> <space> <j> <k> <e> <r> : "┪"
# <Multi_key> <j> <space> <k> <w> <s> : "┭"
# <Multi_key> <j> <space> <k> <r> <f> : "┮"
# <Multi_key> <space> <j> <k> <c> <e> : "┯"
# <Multi_key> <j> <space> <k> <e> <c> : "┰"
# <Multi_key> <space> <j> <k> <f> <r> : "┱"
# <Multi_key> <space> <j> <k> <s> <w> : "┲"
# <Multi_key> <j> <space> <k> <x> <s> : "┵"
# <Multi_key> <j> <space> <k> <v> <f> : "┶"
# <Multi_key> <space> <j> <k> <e> <e> : "┷"
# <Multi_key> <j> <space> <k> <e> <e> : "┸"
# <Multi_key> <space> <j> <k> <f> <v> : "┹"
# <Multi_key> <space> <j> <k> <s> <x> : "┺"
# <Multi_key> <j> <space> <l> <s> <f> : "╞"
# <Multi_key> <space> <j> <l> <f> <s> : "╟"
# <Multi_key> <j> <space> <l> <s> <s> : "╡"
# <Multi_key> <space> <j> <l> <s> <s> : "╢"
# <Multi_key> <space> <j> <l> <c> <e> : "╤"
# <Multi_key> <j> <space> <l> <e> <c> : "╥"
# <Multi_key> <space> <j> <l> <e> <e> : "╧"
# <Multi_key> <j> <space> <l> <e> <e> : "╨"

# <Multi_key> <j> <j> <k> <s> : "┽"
# <Multi_key> <j> <j> <k> <f> : "┾"
# <Multi_key> <j> <k> <s> : "┿"
# <Multi_key> <j> <j> <k> <e> : "╀"
# <Multi_key> <j> <j> <k> <c> : "╁"
# <Multi_key> <j> <k> <e> : "╂"
# <Multi_key> <j> <k> <w> : "╃"
# <Multi_key> <j> <k> <r> : "╄"
# <Multi_key> <j> <k> <x> : "╅"
# <Multi_key> <j> <k> <v> : "╆"
# <Multi_key> <k> <k> <j> <c> : "╇"
# <Multi_key> <k> <k> <j> <e> : "╈"
# <Multi_key> <k> <k> <j> <f> : "╉"
# <Multi_key> <k> <k> <j> <s> : "╊"
# <Multi_key> <j> <l> <s> : "╪"
# <Multi_key> <j> <l> <e> : "╫"

# other

# <Multi_key> <w> <i> <n>                  : "𐌎" U1030e # OLD ITALIC LETTER ESH
# <Multi_key> <m> <o> <u>                  : "🖰" U1f5b0 # TWO BUTTON MOUSE
# <Multi_key> <t> <a> <b>                  : "⭾" U2b7e # HORIZONTAL TAB KEY
# <Multi_key> <b> <a> <c>                  : "⌫" U232b # ERASE TO THE LEFT
# <Multi_key> <c> <o> <m>                  : "⌘" U2318 # PLACE OF INTEREST SIGN
# <Multi_key> <a> <l> <t>                  : "⎇" U2387 # ALTERNATIVE KEY SYMBOL
# <Multi_key> <c> <a> <p>                  : "⇬" U21ec # UPWARDS WHITE ARROW ON PEDESTAL WITH HORIZONTAL BAR
# <Multi_key> <s> <h> <i>                  : "⇧" U21e7 # UPWARDS WHITE ARROW
# <Multi_key> <e> <n> <t>                  : "↵" U21b5 # DOWNWARDS ARROW WITH CORNER LEFTWARDS
# <Multi_key> <b> <u>                      : "⌨" U2328 # KEYBOARD
# <Multi_key> <k> <l> <space>              : "⎡" U23a1 # LEFT SQUARE BRACKET UPPER CORNER
special information: "ℹ"
special warning: "⚠"
# <Multi_key> <r> <o> <t>                  : "↺" U21BA # ANTICLOCKWISE OPEN CIRCLE ARROW
# <Multi_key> <r> <e> <v>                  : "↩" U21A9 # LEFTWARDS ARROW WITH HOOK
# <Multi_key> <p> <i> <c>                  : "🖼" U1F5BC # FRAME WITH PICTURE
# <Multi_key> <v> <i> <d>                  : "🎞" U1F39E # FILM FRAMES
special clock: "⏲"
# <Multi_key> <e> <n> <t>                  : "↵" U21b5 # DOWNWARDS ARROW WITH CORNER LEFTWARDS
# <Multi_key> <c> <o> <n>                  : "└▪↵" # U2514 U25aa U21b5
special tree: "🌲"
special key: "🔑"
# <Multi_key> <p> <o> <s>                  : "⌖" U2316 # POSITION INDICATOR
special flag: "🚩"
# <Multi_key> <f> <i> <r> <s> <t>          : "🌔" U1f314 # WAXING GIBBOUS MOON SYMBOL
# <Multi_key> <e> <m> <p> <t> <y>          : "🌕" U1f315 # FULL MOON SYMBOL
# <Multi_key> <l> <a> <s> <t>              : "🌖" U1f316 # WANING GIBBOUS MOON SYMBOL
# <Multi_key> <r> <e> <s> <t>              : "🌘" U1f318 # WANING CRESCENT MOON SYMBOL
special steps: "👣"
special pin: "📍"
# <Multi_key> <f> <i> <t>                  : "↤⭲⭰↦" # U21a4 U2b72 U2b70 U21a6
# <Multi_key> <d> <a> <t>                  : "📆" U1f4c6 # TEAR-OFF CALENDAR
special person: "🚹"
special point point: "‥"


special one half: "½"
special one third: "⅓"
special one quarter: "¼"
special one fifth: "⅕"
special one sixth: "⅙"
special one seventh: "⅐"
special one eighth: "⅛"
special one ninth: "⅑"
special one tenth: "⅒"
special two thirds: "⅔"
special two fifths: "⅖"
special three quarters: "¾"
special three fifths: "⅗"
special three eighths: "⅜"
special four fifths: "⅘"
special five sixths: "⅚"
special five eighths: "⅝"
special seven eighths: "⅞"
special zero thirds: "↉"

special subscript a: "ₐ"
special subscript e: "ₑ"
special subscript h: "ₕ"
special subscript i: "ᵢ"
special subscript j: "ⱼ"
special subscript k: "ₖ"
special subscript l: "ₗ"
special subscript m: "ₘ"
special subscript n: "ₙ"
special subscript o: "ₒ"
special subscript p: "ₚ"
special subscript r: "ᵣ"
special subscript s: "ₛ"
special subscript t: "ₜ"
special subscript u: "ᵤ"
special subscript v: "ᵥ"
special subscript x: "ₓ"

special ansi bold: "\\u001b[1m \\u001b[0m"

# smiley

special smile: "🙂"
special smile open: "😀"
special sweat: "😅"
special wink: "😉"
special grin: "😬"
special kiss: "😘"
special show tongue: "😛"
special love: "😍"
special heart: "❤️"
special shrug: "🤷"
special cry: "😢"
special open mouth: "😮"
special laugh: "😂"
special fear: "😨"
special poo: "💩"
special thumbs up: "👍"
special thumb down: "👎"
